apiVersion: v1
kind: Pod
metadata:
  labels:
    purpose: jenkins-agent
spec:
  containers:
    - name: simple-agent
      image: k3d-local-registry:5000/jenkins-agente-apictl:3.2.0
      command:
        - cat
      tty: true
